In [3]:
import pandas

In [7]:
dataset = pandas.read_excel("housing RP.xlsx")

In [9]:
import pandas as pd

In [11]:
dataset = pd.read_excel("housing RP.xlsx")

In [13]:
dataset

,title-style,_c819bv,subtitle-style,T_configurationStyle,T_configurationStyle 2,T_blackText 2,T_configurationStyle 3,T_blackText 3,T_configurationStyle 4,T_blackText 4,...,sellerName-label,T_blackTagStyle,T_singlePriceStyle,T_primaryInfoTextStyle,T_primaryInfoTextStyle 2,T_priceStyle,T_marginTop0,T_priceStyle 2,T_marginTop0 2,T_marginTop0 3
0,Mohagaon Town 25 26,RERA,Residential Plots in Wardha Road,1163 sq.ft Plot,1194 sq.ft Plot,â‚¹23.29 L,1208 sq.ft Plot,â‚¹23.56 L,1356 sq.ft Plot,â‚¹26.45 L,...,BHUMESH REALTORS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mauli Town 27,RERA,Residential Plots in Mohgaon,948 sq.ft Plot,1000 sq.ft Plot,â‚¹16.25 L,1100 sq.ft Plot,â‚¹17.88 L,1200 sq.ft Plot,â‚¹19.5 L,...,Mauli developers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mauli Town 21,RERA,Residential Plots in Mohgaon,1000 sq.ft Plot,1100 sq.ft Plot,â‚¹22.55 L,1150 sq.ft Plot,â‚¹23.58 L,1200 sq.ft Plot,â‚¹24.6 L,...,Mauli developers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mauli Town 29,RERA,Residential Plots in Pipla,1100 sq.ft Plot,1134 sq.ft Plot,â‚¹41.66 L,1200 sq.ft Plot,â‚¹44.1 L,1500 sq.ft Plot,â‚¹55.13 L,...,Mauli developers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ayodhya,RERA,Residential Plots in Wathoda Layout,1510 sq.ft Plot,1614 sq.ft Plot,â‚¹56.49 L,1634 sq.ft Plot,â‚¹57.19 L,1661 sq.ft Plot,â‚¹58.14 L,...,Keshvam Properties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Residential Plot / Land in Samruddhi Mahamarg,RERA,Mahalaxmi Nagar 41 Sector 1,Avg. price: â‚¹1.93k/sq.ft,Plot area,NaN,Main entrance facing,NaN,NaN,NaN,...,Vidhan Rangari,New Booking,â‚¹29.02 L,1500 sq.ft,East Facing,NaN,NaN,NaN,NaN,NaN
116,Residential Plot / Land in Samruddhi Mahamarg,RERA,Mahalaxmi Nagar 41 Sector 1,Avg. price: â‚¹2.17k/sq.ft,Plot area,NaN,Main entrance facing,NaN,NaN,NaN,...,Vidhan Rangari,New Booking,â‚¹32.5 L,1500 sq.ft,North east Facing,NaN,NaN,NaN,NaN,NaN
117,Residential Plot / Land in Besa,NaN,NaN,Avg. price: â‚¹4.1k/sq.ft,Plot area,NaN,Main entrance facing,NaN,NaN,NaN,...,Vidhan Rangari,New Booking,â‚¹61.5 L,1500 sq.ft,East Facing,NaN,NaN,NaN,NaN,NaN
118,Residential Plot / Land in Shankarpur,NaN,NaN,Avg. price: â‚¹2.95k/sq.ft,Plot area,NaN,Main entrance facing,NaN,NaN,NaN,...,Pradeep Bisen,Resale,â‚¹33.34 L,1130 sq.ft,North Facing,NaN,NaN,NaN,NaN,NaN
119,Residential Plot / Land in Mihan,NaN,NaN,Avg. price: â‚¹3.9k/sq.ft,Plot area,NaN,Main entrance facing,NaN,NaN,NaN,...,Nilesh Mahajan,New Booking,â‚¹47.23 L,1211 sq.ft,East Facing,NaN,NaN,NaN,NaN,NaN

In [97]:
dataset.info()
dataset.head()
dataset.describe()
dataset.columns

<class 'pandas.core.frame.DataFrame'>
Index: 35 entries, 0 to 36
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   project_name       35 non-null     object
 1   location           35 non-null     object
 2   area_sqft          35 non-null     float64
 3   price_lakh         35 non-null     float64
 4   developer          35 non-null     object
 5   price_per_sqft     35 non-null     float64
 6   location_encoded   35 non-null     int32
 7   developer_encoded  35 non-null     int32
dtypes: float64(3), int32(2), object(3)
memory usage: 2.2+ KB

Index(['project_name', 'location', 'area_sqft', 'price_lakh', 'developer',
       'price_per_sqft', 'location_encoded', 'developer_encoded'],
      dtype='object')

In [ ]:
df = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']]
df.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

In [101]:
# Convert to string before cleaning
dataset.loc[:, 'price_lakh'] = dataset['price_lakh'].astype(str)

# Remove ₹ and 'Lacs', strip spaces
dataset.loc[:, 'price_lakh'] = dataset['price_lakh'].str.replace('₹', '', regex=False)
dataset.loc[:, 'price_lakh'] = dataset['price_lakh'].str.replace('Lacs', '', regex=False)
dataset.loc[:, 'price_lakh'] = dataset['price_lakh'].str.strip()

# Convert cleaned string to float
dataset.loc[:, 'price_lakh'] = pd.to_numeric(dataset['price_lakh'], errors='coerce')

In [105]:
# Step 1: Convert to string type
dataset['price_lakh'] = dataset['price_lakh'].astype(str)

# Step 2: Remove unwanted characters (₹, Lacs, commas, spaces)
dataset['price_lakh'] = (
    dataset['price_lakh']
    .str.replace('₹', '', regex=False)
    .str.replace('Lacs', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

# Step 3: Convert cleaned text back to numeric values
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'], errors='coerce')

In [107]:
dataset.loc[:, 'location'] = dataset['location'].astype(str).str.lower().str.strip()

In [109]:
dataset = dataset.loc[dataset[['location', 'price_lakh', 'area_sqft']].notnull().all(axis=1)]

In [111]:
# Compute price per square foot: (price in ₹) / area in sqft
dataset = dataset.copy()  # Ensure we're working on a proper DataFrame, not a view
dataset['price_per_sqft'] = (dataset['price_lakh'] * 100000) / dataset['area_sqft']

In [113]:
# Remove outliers for price per sqft (optional, based on domain knowledge)
dataset = dataset[(dataset['price_per_sqft'] > 1000) & (dataset['price_per_sqft'] < 100000)]

In [115]:
dataset = pd.get_dummies(dataset, columns=['location', 'developer'], drop_first=True)

In [117]:
print(dataset.columns)

Index(['project_name', 'area_sqft', 'price_lakh', 'price_per_sqft',
       'location_encoded', 'developer_encoded',
       'location_residential plots  in beltarodi',
       'location_residential plots  in besa',
       'location_residential plots  in bothali',
       'location_residential plots  in hingna',
       'location_residential plots  in jamtha',
       'location_residential plots  in lava',
       'location_residential plots  in mihan',
       'location_residential plots  in mohgaon',
       'location_residential plots  in panjari farm',
       'location_residential plots  in pipla',
       'location_residential plots  in samruddhi mahamarg',
       'location_residential plots  in shankarpur',
       'location_residential plots  in wagdara',
       'location_residential plots  in wardha road',
       'location_residential plots  in wathoda layout',
       'location_residential plots  in yerla', 'developer_bhumesh realtors',
       'developer_dera developers',
       'developer_design developers private limited',
       'developer_keshvam  properties', 'developer_leverage group',
       'developer_mahalaxmi developers', 'developer_mahalaxmi infra',
       'developer_matoshree developers', 'developer_mauli developers',
       'developer_oasis infraspace pvt ltd',
       'developer_ozen realtors india pvt. ltd.',
       'developer_princelands developers', 'developer_privara developers llp',
       'developer_sandeep dwellers pvt ltd', 'developer_shiv rudra group',
       'developer_shrivalli infra'],
      dtype='object')

In [119]:
# Reload original data (adjust filename if needed)
import pandas as pd
df = pd.read_excel('housing RP.xlsx')  # or your local path

# Select required columns again
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']]
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

In [121]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Step 1: Load original Excel file
df = pd.read_excel('housing RP.xlsx')  # Or your correct path

# Step 2: Select needed columns and create a clean copy
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']].copy()
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

# Step 3: Clean text columns safely
dataset.loc[:, 'location'] = dataset['location'].astype(str).str.lower().str.strip()
dataset.loc[:, 'developer'] = dataset['developer'].astype(str).str.lower().str.strip()

# Step 4: Encode categorical columns without warnings
le_loc = LabelEncoder()
le_dev = LabelEncoder()

dataset.loc[:, 'location_encoded'] = le_loc.fit_transform(dataset['location'])
dataset.loc[:, 'developer_encoded'] = le_dev.fit_transform(dataset['developer'])

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [123]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load your Excel file
df = pd.read_excel('housing RP.xlsx')

# Select and rename the relevant columns
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']].copy()
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

# Clean text
dataset['location'] = dataset['location'].astype(str).str.lower().str.strip()
dataset['developer'] = dataset['developer'].astype(str).str.lower().str.strip()

# Encode categorical data
le_loc = LabelEncoder()
le_dev = LabelEncoder()
dataset['location_encoded'] = le_loc.fit_transform(dataset['location'])
dataset['developer_encoded'] = le_dev.fit_transform(dataset['developer'])

In [125]:
# Convert area and price to numeric
dataset['area_sqft'] = pd.to_numeric(dataset['area_sqft'].astype(str).str.replace(',', ''), errors='coerce')
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'].astype(str).str.replace(',', ''), errors='coerce')

In [129]:
# Check missing values
print(dataset.isnull().sum())

# Option: Drop rows with missing values (or you can impute with mean/median)
dataset.dropna(inplace=True)

project_name         0
location             0
area_sqft            0
price_lakh           0
developer            0
location_encoded     0
developer_encoded    0
dtype: int64

In [13]:
dataset['price_per_sqft'] = dataset['price_lakh'] * 100000 / dataset['area_sqft']

In [15]:
final_data = dataset[['area_sqft', 'price_lakh', 'price_per_sqft', 'location_encoded', 'developer_encoded']]

In [19]:
dataset.to_excel('cleaned_housing_data.xlsx', index=False)

In [21]:
final_data.to_excel('final_housing_data.xlsx', index=False)

In [23]:
print(dataset.shape)
print(dataset.head())

(0, 8)
Empty DataFrame
Columns: [project_name, location, area_sqft, price_lakh, developer, location_encoded, developer_encoded, price_per_sqft]
Index: []

In [55]:
dataset['area_sqft'] = pd.to_numeric(dataset['area_sqft'].astype(str).str.replace(',', ''), errors='coerce')
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'].astype(str).str.replace(',', ''), errors='coerce')

In [31]:
dataset.dropna(inplace=True)

In [49]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load original file
df = pd.read_excel('housing RP.xlsx')  # Make sure the path is correct

# Select and rename columns
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']].copy()
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

# Clean text columns
dataset['location'] = dataset['location'].astype(str).str.lower().str.strip()
dataset['developer'] = dataset['developer'].astype(str).str.lower().str.strip()

# Encode categorical values
le_loc = LabelEncoder()
le_dev = LabelEncoder()
dataset['location_encoded'] = le_loc.fit_transform(dataset['location'])
dataset['developer_encoded'] = le_dev.fit_transform(dataset['developer'])

# Convert area_sqft and price_lakh to numeric
dataset['area_sqft'] = pd.to_numeric(dataset['area_sqft'].astype(str).str.replace(',', ''), errors='coerce')
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'].astype(str).str.replace(',', ''), errors='coerce')

# Drop rows where area or price is missing or zero
dataset = dataset.dropna(subset=['area_sqft', 'price_lakh'])
dataset = dataset[(dataset['area_sqft'] > 0) & (dataset['price_lakh'] > 0)]

# Create price per sqft column
dataset['price_per_sqft'] = (dataset['price_lakh'] * 100000) / dataset['area_sqft']

# Final cleaned dataset
final_data = dataset[['area_sqft', 'price_lakh', 'price_per_sqft', 'location_encoded', 'developer_encoded']]

# Save to Excel
final_data.to_excel('final_housing_data_cleaned.xlsx', index=False)

In [51]:
final_data.head(10)

Empty DataFrame
Columns: [area_sqft, price_lakh, price_per_sqft, location_encoded, developer_encoded]
Index: []

In [23]:
print("Rows and columns:", final_data.shape)

Rows and columns: (0, 5)

In [25]:
print("After cleaning:")
print(dataset.head(10))

After cleaning:
Empty DataFrame
Columns: [project_name, location, area_sqft, price_lakh, developer, location_encoded, developer_encoded, price_per_sqft]
Index: []

In [27]:
print("Rows before dropping NA and zeroes:", df.shape)
print("Rows after dropping NA and zeroes:", dataset.shape)

Rows before dropping NA and zeroes: (120, 37)
Rows after dropping NA and zeroes: (0, 8)

In [29]:
'title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label'

('title-style',
 'subtitle-style',
 'T_configurationStyle',
 'T_blackText 2',
 'sellerName-label')

In [31]:
# Check rows before filtering
print("Before filtering:")
print(dataset[['area_sqft', 'price_lakh']].head(10))

# Check rows removed
print("Rows removed due to NaN or 0s:")
print(dataset[(dataset['area_sqft'].isna()) | (dataset['price_lakh'].isna()) | 
              (dataset['area_sqft'] <= 0) | (dataset['price_lakh'] <= 0)].shape)

Before filtering:
Empty DataFrame
Columns: [area_sqft, price_lakh]
Index: []
Rows removed due to NaN or 0s:
(0, 8)

In [33]:
# Check raw values from original dataframe
print(df[['T_configurationStyle', 'T_blackText 2']].head(10))

  T_configurationStyle T_blackText 2
0      1163 sq.ft Plot    â‚¹23.29 L
1       948 sq.ft Plot    â‚¹16.25 L
2      1000 sq.ft Plot    â‚¹22.55 L
3      1100 sq.ft Plot    â‚¹41.66 L
4      1510 sq.ft Plot    â‚¹56.49 L
5      1049 sq.ft Plot    â‚¹32.39 L
6      1091 sq.ft Plot    â‚¹25.62 L
7      1200 sq.ft Plot     â‚¹13.0 L
8       818 sq.ft Plot           NaN
9      1029 sq.ft Plot    â‚¹22.81 L

In [35]:
print(df[['T_configurationStyle', 'T_blackText 2']].dtypes)

T_configurationStyle    object
T_blackText 2           object
dtype: object

In [37]:
# Check raw values without conversion
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']].copy()
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

# Just show the raw values
print(dataset[['area_sqft', 'price_lakh']].head(10))

         area_sqft  price_lakh
0  1163 sq.ft Plot  â‚¹23.29 L
1   948 sq.ft Plot  â‚¹16.25 L
2  1000 sq.ft Plot  â‚¹22.55 L
3  1100 sq.ft Plot  â‚¹41.66 L
4  1510 sq.ft Plot  â‚¹56.49 L
5  1049 sq.ft Plot  â‚¹32.39 L
6  1091 sq.ft Plot  â‚¹25.62 L
7  1200 sq.ft Plot   â‚¹13.0 L
8   818 sq.ft Plot         NaN
9  1029 sq.ft Plot  â‚¹22.81 L

In [41]:
# Clean area_sqft
dataset['area_sqft'] = dataset['area_sqft'].astype(str).str.extract(r'(\d+\.?\d*)')
dataset['area_sqft'] = pd.to_numeric(dataset['area_sqft'], errors='coerce')

# Clean price_lakh
dataset['price_lakh'] = dataset['price_lakh'].astype(str)
dataset['price_lakh'] = dataset['price_lakh'].str.replace(r'[^\d.]', '', regex=True)

# Replace empty strings with NaN before converting to float
dataset['price_lakh'] = dataset['price_lakh'].replace('', pd.NA)
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'], errors='coerce')

In [43]:
# Drop missing or zero values
dataset = dataset.dropna(subset=['area_sqft', 'price_lakh'])
dataset = dataset[(dataset['area_sqft'] > 0) & (dataset['price_lakh'] > 0)]

# Price per sqft
dataset['price_per_sqft'] = (dataset['price_lakh'] * 100000) / dataset['area_sqft']

In [45]:
dataset.head(10)

,project_name,location,area_sqft,price_lakh,developer,price_per_sqft
0,Mohagaon Town 25 26,Residential Plots in Wardha Road,1163.0,23.29,BHUMESH REALTORS,2002.579536
1,Mauli Town 27,Residential Plots in Mohgaon,948.0,16.25,Mauli developers,1714.135021
2,Mauli Town 21,Residential Plots in Mohgaon,1000.0,22.55,Mauli developers,2255.000000
3,Mauli Town 29,Residential Plots in Pipla,1100.0,41.66,Mauli developers,3787.272727
4,Ayodhya,Residential Plots in Wathoda Layout,1510.0,56.49,Keshvam Properties,3741.059603
5,Mahalaxmi Nagar 40,Residential Plots in Samruddhi Mahamarg,1049.0,32.39,Mahalaxmi Infra,3087.702574
6,Mahalaxmi Nagar 41 Phase II,Residential Plots in Samruddhi Mahamarg,1091.0,25.62,Mahalaxmi Infra,2348.304308
7,Dera Greens 3,Residential Plots in Yerla,1200.0,13.00,Dera Developers,1083.333333
9,Mahalaxmi Nagar 42,Residential Plots in Jamtha,1029.0,22.81,Mahalaxmi Developers,2216.715258
10,Privara Golden Avenue,Residential Plots in Besa,1292.0,62.00,Privara Developers LLP,4798.761610

In [47]:
from IPython.display import display
display(dataset)

,project_name,location,area_sqft,price_lakh,developer,price_per_sqft
0,Mohagaon Town 25 26,Residential Plots in Wardha Road,1163.0,23.29,BHUMESH REALTORS,2002.579536
1,Mauli Town 27,Residential Plots in Mohgaon,948.0,16.25,Mauli developers,1714.135021
2,Mauli Town 21,Residential Plots in Mohgaon,1000.0,22.55,Mauli developers,2255.000000
3,Mauli Town 29,Residential Plots in Pipla,1100.0,41.66,Mauli developers,3787.272727
4,Ayodhya,Residential Plots in Wathoda Layout,1510.0,56.49,Keshvam Properties,3741.059603
5,Mahalaxmi Nagar 40,Residential Plots in Samruddhi Mahamarg,1049.0,32.39,Mahalaxmi Infra,3087.702574
6,Mahalaxmi Nagar 41 Phase II,Residential Plots in Samruddhi Mahamarg,1091.0,25.62,Mahalaxmi Infra,2348.304308
7,Dera Greens 3,Residential Plots in Yerla,1200.0,13.00,Dera Developers,1083.333333
9,Mahalaxmi Nagar 42,Residential Plots in Jamtha,1029.0,22.81,Mahalaxmi Developers,2216.715258
10,Privara Golden Avenue,Residential Plots in Besa,1292.0,62.00,Privara Developers LLP,4798.761610
11,Krishna Nagari,Residential Plots in Jamtha,1451.0,35.51,Privara Developers LLP,2447.277739
13,Lakeshore Oasis,Residential Plots in Besa,1744.0,68.10,Leverage Group,3904.816514
14,Florence,Residential Plots in Hingna,1200.0,20.00,Matoshree Developers,1666.666667
15,Mukunda Keshavam 9,Residential Plots in Wagdara,2100.0,50.49,Keshvam Properties,2404.285714
16,Nirmal Keshavam 15,Residential Plots in Panjari farm,1103.0,34.47,Keshvam Properties,3125.113327
17,Mauli Nagar 17 Sec A,Residential Plots in Shankarpur,1000.0,39.07,Mauli developers,3907.000000
18,Nivaasa Retreat,Residential Plots in Shankarpur,1100.0,32.66,Shrivalli Infra,2969.090909
19,AGI Colony,Residential Plots in Samruddhi Mahamarg,1149.0,22.00,Shrivalli Infra,1914.708442
20,Samruddhi Estate I,Residential Plots in Samruddhi Mahamarg,853.0,9.40,Shrivalli Infra,1101.992966
21,Silver Park 15,Residential Plots in Shankarpur,1240.0,41.33,Balaji Group,3333.064516
22,Ozen Infinia City,Residential Plots in Mohgaon,850.0,14.17,Ozen Realtors India Pvt. Ltd.,1667.058824
23,Balaji Silver Star 1,Residential Plots in Amravati Road,1033.0,20.34,Balaji Group,1969.022265
24,Balaji Silver Icon,Residential Plots in Beltarodi,1091.0,43.51,Balaji Group,3988.084326
25,AGI Residency,Residential Plots in Hingna,1017.0,27.33,Princelands Developers,2687.315634
26,Vrindavan Park,Residential Plots in Hingna,1000.0,26.95,Balaji Group,2695.000000
27,Anandam 14,Residential Plots in Wardha Road,1100.0,45.60,Design Developers Private Limited,4145.454545
28,Gulmohar Greens 1,Residential Plots in Wardha Road,1235.0,23.92,Shrivalli Infra,1936.842105
29,Matoshree Nagar 1,Residential Plots in Mihan,1089.0,22.16,Matoshree Developers,2034.894399
30,Oasis 34,Residential Plots in Mihan,941.0,47.23,Oasis Infraspace Pvt Ltd,5019.128587
31,Aaranyam,Residential Plots in Lava,1055.0,34.14,Sandeep Dwellers Pvt Ltd,3236.018957
32,Vasant Vihar,Residential Plots in Besa,1143.0,31.39,Oasis Infraspace Pvt Ltd,2746.281715
33,Karamchand Greens,Residential Plots in Jamtha,1100.0,33.75,SHIV RUDRA GROUP,3068.181818
34,Matoshree Ruchi Empire Phase 1,Residential Plots in Bothali,1000.0,22.64,Matoshree Developers,2264.000000
35,Godrej Forest Estate,Residential Plots in Samruddhi Mahamarg,1100.0,52.00,SHIV RUDRA GROUP,4727.272727
36,Kanchan Nagari 13,Residential Plots in Hingna,1081.0,20.34,Matoshree Developers,1881.591119

In [57]:
# Count rows before and after
print("Original rows:", len(df))

# Step-by-step analysis
df_temp = dataset.copy()

# Show rows with invalid area
invalid_area = df_temp[df_temp['area_sqft'].isna()]
print("\nRows with invalid area_sqft:", len(invalid_area))

# Show rows with invalid price
invalid_price = df_temp[df_temp['price_lakh'].isna()]
print("Rows with invalid price_lakh:", len(invalid_price))

# Show rows with zero values
zero_rows = df_temp[(df_temp['area_sqft'] <= 0) | (df_temp['price_lakh'] <= 0)]
print("Rows with 0 in area or price:", len(zero_rows))

# Final row count
print("\nFinal usable rows:", len(dataset))

Original rows: 120

Rows with invalid area_sqft: 0
Rows with invalid price_lakh: 0
Rows with 0 in area or price: 0

Final usable rows: 0

In [59]:
# If using final_data (cleaned + encoded)
final_data.to_excel('final_housing_data_cleaned.xlsx', index=False)

# OR if you're using dataset before final selection
dataset.to_excel('cleaned_housing_data.xlsx', index=False)

In [77]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load original file
df = pd.read_excel('housing RP.xlsx')

# Select and rename columns
dataset = df[['title-style', 'subtitle-style', 'T_configurationStyle', 'T_blackText 2', 'sellerName-label']].copy()
dataset.columns = ['project_name', 'location', 'area_sqft', 'price_lakh', 'developer']

# Extract numeric area
dataset['area_sqft'] = dataset['area_sqft'].astype(str).str.extract(r'(\d+\.?\d*)')
dataset['area_sqft'] = pd.to_numeric(dataset['area_sqft'], errors='coerce')

# Extract numeric price
dataset['price_lakh'] = dataset['price_lakh'].astype(str).str.replace(r'[^\d.]', '', regex=True)
dataset['price_lakh'] = dataset['price_lakh'].replace('', pd.NA)
dataset['price_lakh'] = pd.to_numeric(dataset['price_lakh'], errors='coerce')

# Drop bad rows
dataset = dataset.dropna(subset=['area_sqft', 'price_lakh'])
dataset = dataset[(dataset['area_sqft'] > 0) & (dataset['price_lakh'] > 0)]

# Compute price per sqft
dataset['price_per_sqft'] = (dataset['price_lakh'] * 100000) / dataset['area_sqft']

# Encode text
le_loc = LabelEncoder()
le_dev = LabelEncoder()
dataset['location'] = dataset['location'].astype(str).str.lower().str.strip()
dataset['developer'] = dataset['developer'].astype(str).str.lower().str.strip()
dataset['location_encoded'] = le_loc.fit_transform(dataset['location'])
dataset['developer_encoded'] = le_dev.fit_transform(dataset['developer'])

# Final cleaned dataset
final_data = dataset[['area_sqft', 'price_lakh', 'price_per_sqft', 'location_encoded', 'developer_encoded']]

# Confirm it has rows
print("Final row count:", final_data.shape[0])

# Save to Excel
final_data.to_excel('final_housing_data_cleaned.xlsx', index=False)

Final row count: 35

In [79]:
final_data.to_excel('final_housing_data_cleaned.xlsx', index=False)